<a href="https://colab.research.google.com/github/doSwayamCode/ml-daily/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Day-1 **

In [ ]:
import numpy as np
import pandas as pd
import sklearn
import tensorflow as tf

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)
print("Scikit-learn version:", sklearn.__version__)
print("TensorFlow version:", tf.__version__)



NumPy version: 1.26.4
Pandas version: 2.2.2
Scikit-learn version: 1.6.1
TensorFlow version: 2.18.0


In [ ]:
!pip install numpy


In [ ]:
import numpy as np

#create array
arr = np.array([1, 2, 3, 4, 5])

#print array
print(arr)

[1 2 3 4 5]


In [ ]:
arr.shape

(5,)

In [ ]:
arr.sum()

15

In [ ]:
#create 3x3 matrix

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
!pip install pandas


In [ ]:
import pandas as pd

# Creating a DataFrame
data = {'Name': ['Swayam', 'Vansh', 'Dev'],
        'Age': [22, 20, 21]}
df = pd.DataFrame(data)
print(df)


     Name  Age
0  Swayam   22
1   Vansh   20
2     Dev   21


In [ ]:
# lets create a Pandas dataframe with 5 rows
data = {'Name': ['Swayam', 'Vansh', 'Dev','Vaibhav', 'Sonu'],
        'Age' :[22,20,21,22,22],
        'Salary':[100000, 150000, 160000, 200000, 400000]}

df= pd.DataFrame(data)
print(df)

      Name  Age  Salary
0   Swayam   22  100000
1    Vansh   20  150000
2      Dev   21  160000
3  Vaibhav   22  200000
4     Sonu   22  400000


In [ ]:
# Load Titanic dataset
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Check first few rows
print(df.head())


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [ ]:
#number of passengers in titanic
df.shape

(891, 12)

In [ ]:
# avg age of passengers which is 30 years.
df['Age'].mean()

29.69911764705882

In [ ]:
#how many passengers survived
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64