In [1]:
import numpy as np


In [5]:
a = np.array([1, 2, 3, 4, 5])

In [6]:
print(a)

[1 2 3 4 5]


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [10]:
print(a[1:])
# 1 until the end (excluding 1)

[2 3 4 5]


In [11]:
print(a[:-2])
# up until the last 2 (excluding -2)

[1 2 3]


In [12]:
a[2]=10

In [13]:
a

array([ 1,  2, 10,  4,  5])

In [15]:
a_mul = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

In [16]:
a_mul

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a_mul[0,1]


np.int64(2)

In [19]:
print(a_mul.shape)

(3, 3)


In [ ]:
print(a_mul.ndim)
# dimension of list

2


In [22]:
print(a_mul.size)

9


In [23]:
print(a_mul.dtype)

int64


In [33]:
a= np.array([[1,2,3],
             [4,"5",6],
             [7,8,9]], dtype=np.int32)

# you can specify the datatype to typecast it.

In [34]:
print(a.dtype)

int32


In [35]:
print(a[0][0].dtype)

int32


# functions

In [38]:
a= np.full((2,3,4), 9)
# first we fill shape of the array, then the value to fill it with.

In [40]:
print(a)
# how to read (2,3,4) : it consists of 2 arrays, each of them has 3 arrays, and each of them has 4 elements.

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [41]:
a= np.zeros((10,5,2))

In [42]:
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [43]:
a=np.ones((10,5,2))

In [44]:
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [45]:
a = np.empty((5,5,5))

In [46]:
print(a)

[[[0.00000000e+000 6.95174635e-310 4.67386101e-321             nan
   1.30127136e-311]
  [2.07458463e+026 9.08367229e+223 1.69375010e+190 2.87453085e+291
   3.14405836e+233]
  [8.54265717e+257 6.99177894e+228 8.24242019e+160 1.26829177e+017
   5.79530389e+199]
  [7.47730573e+247 4.44389100e+252 1.84841356e-004 4.24515351e+175
   3.33747054e+257]
  [5.42791239e-109 6.99177729e+228 4.78206908e+180 8.23560879e+160
   1.09060199e-114]]

 [[6.99177794e+228 3.64393095e+228 1.06303599e+224 6.97873719e+228
   1.94933351e+243]
  [2.65648976e+233 1.14131281e-114 3.93266695e-028 8.89501052e+252
   4.69598393e+257]
  [1.67751539e+243 7.36093992e+223 2.86121962e+242 2.28898721e+243
   1.69375270e+190]
  [2.58634340e+161 3.18274026e+291 1.94927295e+243 8.44747281e+252
   1.67751539e+243]
  [1.69375270e+190 1.86390505e-004 6.92546575e+252 6.51629129e-109
   7.54178159e+252]]

 [[1.21130561e+199 6.77202251e-109 4.31579898e+055 1.94923879e+243
   7.27373220e+175]
  [5.32751130e+233 4.11941833e+257 1.87

In [50]:
x_value = np.arange(0,1005,5)

In [51]:
print(x_value)

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

In [55]:
x_values = np.linspace(0,1000, 5)

In [56]:
print(x_values)

[   0.  250.  500.  750. 1000.]


In [57]:
print(np.nan)
print(np.inf)

nan
inf


In [ ]:
print(np.sqrt(-1))
print(np.array([10]) / 0)

True
[ True]


C:\Users\Swayam\AppData\Local\Temp\ipykernel_15308\1011850589.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))
C:\Users\Swayam\AppData\Local\Temp\ipykernel_15308\1011850589.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10]) / 0))


In [61]:
l1= [1,2,3,4,5]
l2= [6,7,8,9,10]

In [62]:
a1 = np.array(l1)
a2 = np.array(l2)

In [63]:
print(l1 *5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [64]:
print(a1 * 5)

[ 5 10 15 20 25]


In [65]:
print(l1 + l2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [66]:
print(a1 + a2)

[ 7  9 11 13 15]


In [67]:
print(a1 *a2)

[ 6 14 24 36 50]


In [68]:
print(a1/a2)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [69]:
a1 = np.array([1,2,3])
a2 = np.array([[1],
               [2]])

In [70]:
print(a1 + a2)

[[2 3 4]
 [3 4 5]]


In [71]:
a = np.array([[1,2,3],
              [4,5,6]])

In [73]:
print(np.sin(a))
# we have sin, cos, tan, exp, log, sqrt etc.

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [74]:
a = np.array([1,2,3])

In [75]:
print(np.append(a, [4,5,6]))
print(a)
# append adds the values to the end of the array.

[1 2 3 4 5 6]
[1 2 3]


In [76]:
a

array([1, 2, 3])

In [77]:
a= np.append(a, [[7,8,9]])  

In [78]:
print(a)

[1 2 3 7 8 9]


In [ ]:
a=np.insert(a, 3, [4,5,6])  
# 3 is the index where we want to insert the values, and [4,5,6] are the values to be inserted.

In [82]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [83]:
print(np.delete(a, 1))
print(np.delete(a, 3))
print(np.delete(a, 5))

[1 3 4 5 6 7 8 9]
[1 2 3 5 6 7 8 9]
[1 2 3 4 5 7 8 9]


In [ ]:
print(np.delete(a, 1, 0))
# 0 is the axis, 1 is the column. So we are deleting the first row.

[1 3 4 5 6 7 8 9]


In [85]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])
# 2D array with shape (4,5), 4 rows and 5 columns.

In [86]:
print(a.shape)

(4, 5)


In [87]:
print(a.reshape(5,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [88]:
print(a.reshape((20,)))
# 1D array with shape (20,) means it has 20 elements in a single row.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [89]:
print(a.reshape((20,1)))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


In [90]:
print(a.reshape((2,10)))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [91]:
print(a.reshape((5,2,2)))
# 3D array with shape (5,2,2) means it has 5 arrays, each of them has 2 arrays, and each of them has 2 elements.
# 5 arrays, each of them has 2 arrays, and each of them has 2 elements.

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [ ]:
print(a.reshape((1,1,1,1,2,10)))
# 6D array with shape (1,1,1,1,2,10) means it has 1 array, each of them has 1 array, and each of them has 1 array, and each of them has 2 arrays, and each of them has 10 elements.
# 1 array, each of them has 1 array, and each of them has 1 array, and each of them has 2 arrays, and each of them has 10 elements.

[[[[[[ 1  2  3  4  5  6  7  8  9 10]
     [11 12 13 14 15 16 17 18 19 20]]]]]]


In [93]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [94]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [96]:
a.resize((10,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [97]:
print(a.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [98]:
print(a.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
print(a.flatten())
print(a.ravel())

var1 = a.flatten()
var1[2] = 100
print(var1)
print(a)
# dont change the original array, because flatten creates a copy of the original array.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [ ]:
var1 = a.ravel()
var1[2] = 100
print(var1)
print(a)
# changes the array

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2]
 [100   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [ 11  12]
 [ 13  14]
 [ 15  16]
 [ 17  18]
 [ 19  20]]


In [101]:
var = [v for v in a.flat]
print(var)

[np.int64(1), np.int64(2), np.int64(100), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]


# Transposing and other functions


In [102]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

In [104]:
print(a.transpose())

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [105]:
print(a.T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [106]:
print(a.swapaxes(0,1))

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [108]:
a1 = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

a2= np.array([[11,12,13,14,15],
              [16,17,18,19,20]])
             

In [ ]:
a = np.concatenate((a1,a2), axis=0)
print(a)
# axis=0 means we are concatenating the arrays vertically, axis=1 means we are concatenating the arrays horizontally.   

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [110]:
a = np.concatenate((a1,a2), axis=1)
print(a)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [111]:
a = np.stack((a1,a2))
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [112]:
a = np.vstack((a1,a2))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [113]:
a = np.hstack((a1,a2))
print(a)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [114]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])

In [115]:
print(np.split(a, 2, axis=0))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]


In [116]:
print(np.split(a, 4, axis=0))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])]


In [123]:
a = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18],
              [19,20,21,22,23,24]])

In [124]:
print(np.split(a, 2, axis=1))

[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]


In [125]:
print(np.split(a, 3, axis=1))

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]


In [126]:
print(np.split(a, 6, axis=1))

[array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2],
       [ 8],
       [14],
       [20]]), array([[ 3],
       [ 9],
       [15],
       [21]]), array([[ 4],
       [10],
       [16],
       [22]]), array([[ 5],
       [11],
       [17],
       [23]]), array([[ 6],
       [12],
       [18],
       [24]])]


In [128]:
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())
print(np.median(a))

1
24
12.5
6.922186552431729
300
12.5


In [132]:
numbers = np.random.randint(90,100, size =(2,3,4))
print(numbers)

[[[98 92 97 99]
  [93 97 99 95]
  [94 99 98 90]]

 [[90 94 90 97]
  [99 95 95 97]
  [93 94 92 94]]]


In [135]:
numbers = np.random.binomial(10, p=0.5, size=(5,10))
print(numbers)

[[5 5 5 8 5 7 4 3 4 6]
 [2 7 3 4 1 4 4 6 2 5]
 [5 7 5 5 6 7 4 7 7 3]
 [1 5 5 6 8 4 6 7 8 5]
 [7 5 6 5 4 5 5 4 4 4]]


In [138]:
numbers = np.random.choice([10,20,30,40,50], size = (5,10))
print(numbers)

[[10 10 30 30 10 50 40 40 10 50]
 [30 50 50 50 40 20 20 50 50 10]
 [20 40 50 50 40 30 30 50 20 40]
 [10 10 50 20 20 40 40 10 10 40]
 [20 10 10 10 40 30 40 40 10 20]]


In [139]:
np.save("myArray.npy", a)

In [140]:
a = np.load("myArray.npy")
print(a)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [142]:
np.savetxt("myArray.csv", a, delimiter=",")

In [143]:
a= np.loadtxt("myArray.csv", delimiter=",")
print(a)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]]
